# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target '20210301_COVID19' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 20210301_COVID19
  pod 'Firebase'
  pod 'FSCalendar'
  pod 'Charts'
  pod 'CalculateCalendarLogic'
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'MessageKit'
  pod 'MessageInputBar'
  pod 'PKHUD'


  target '20210301_COVID19Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '20210301_COVID19UITests' do
    # Pods for testing
  end

end
